#%RAML 1.0
title: eAPI - Portal Service
baseUri: https://mocksvc.mulesoft.com/mocks/82fd6c8f-2c5e-48c4-b306-1e6a1babcd34/portal # baseUri: http://localhost:8081/portal
version: 1.0
/login:
  post:
    displayName: Get user profile
    description: Authenticate user and get user profile
    body:
      application/json:
        example: |
          {
            "user_id": "s8187903f",
            "password": "password3"
          }
    responses:
      200:
        description: return the list of accounts
        body:
          application/json:
            example: |
              {
                "change_password_required": true,
                "name": "BXXCEXXXXXFE",
                "user_id": "s8187903f",
                "bp_numbers": [
                  {
                    "bp_number": "1003326931",
                    "system": "EBS"
                  },
                  {
                    "bp_number": "7000043525",
                    "system": "MSSL"
                  }
                ],
                "email": "nelsonwee@spgroup.com.sg",
                "mobile": "90000000",
                "premises": [
                  {
                    "accounts": [
                      {
                        "system": "EBS",
                        "premise_number": "2001696810",
                        "account_number": "008933084488",
                        "account_status": "Active",
                        "account_type": "DOM",
                        "bp_number": "1003326931",
                        "address": "880 UPP BT TIMAH RD #01-04 SINGAPORE 678181",
                        "mailing_address": {
                          "block_or_apartment": "880",
                          "street": "UPP BT TIMAH RD",
                          "unit": "#01-04",
                          "postal_code": "678181"
                        },
                        "utilities": [
                          "water",
                          "gas"
                        ],
                        "ami": false
                      },
                      {
                        "system": "MSSL",
                        "premise_number": "6100051650",
                        "account_number": "009301581303",
                        "account_status": "Active",
                        "account_type": "DOM",
                        "bp_number": "7000043525",
                        "address": "880 UPP BT TIMAH RD #01-04 SINGAPORE 678181",
                        "mailing_address": {
                          "block_or_apartment": "880",
                          "street": "UPP BT TIMAH RD",
                          "unit": "#01-04",
                          "postal_code": "678181"
                        },
                        "utilities": [
                          "electric"
                        ],
                        "ami": true
                      }
                    ]
                  }
                ]
              }
